let obj = {
    "code": 1,
    "data": [{
        "id": "31",
        "title": "企业安全生产举报",
        "url": "http://sdaj.gov.cn/aqsc/yjt12345.html",
        "thumb": "https://img11.iqilu.com/0/icons/weifuwu_safe.png"
    }, {
        "id": "32",
        "title": "山东疫情检测查询",
        "url": "http://bj.msunsoft.com/yq/pages/notification-mobile/#/shandong",
        "thumb": "https://img11.iqilu.com/0/icons/weifuwu_yiqing.png"
    }, {
        "id": "1",
        "title": "火车票",
        "url": "https://m.ctrip.com/webapp/train/?allianceid=262735&sid=711516&sepopup=70&autoawaken=close",
        "thumb": "http://app.iqilu.com/service/service/images/720e039db76f4353a2bbb846d3ec9911.png"
    }, {
        "id": "2",
        "title": "飞机票",
        "url": "https://m.ctrip.com/html5/Flight/?allianceid=262735&sid=711516&sepopup=70&autoawaken=close",
        "thumb": "http://app.iqilu.com/service/service/images/7386c692a21049a79c3d0d53a05db8ab.png"
    }, {
        "id": "3",
        "title": "天气预报",
        "url": "https://www.msn.cn/zh-cn/weather/today/%E5%B1%B1%E4%B8%9C%E7%9C%81%E6%BD%8D%E5%9D%8A%E5%B8%82%E5%B1%B1%E4%B8%9C%E7%9C%81%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD/we-city?q=%E5%B1%B1%E4%B8%9C%E7%9C%81%E6%BD%8D%E5%9D%8A%E5%B8%82-%E5%B1%B1%E4%B8%9C%E7%9C%81&form=PRWLAS&el=f7vT%2fCwNk44LyyUQ0KTkCw%3d%3d",
        "thumb": "http://app.iqilu.com/service/service/images/31182d91de4b419289916c6c252d4843.png"
    }, {
        "id": "4",
        "title": "百度出行",
        "url": "https://map.baidu.com/mobile/webapp/index/moretravel/",
        "thumb": "http://app.iqilu.com/service/service/images/19207dfe3d184cbc9fcb199c18817a4e.png"
    }, {
        "id": "5",
        "title": "PM2.5查询",
        "url": "http://m.pm25.com",
        "thumb": "http://app.iqilu.com/service/service/images/439660187ff7462fbac993df53afb92e.png"
    }, {
        "id": "6",
        "title": "家政",
        "url": "https://m.daojia.com",
        "thumb": "http://app.iqilu.com/service/service/images/6fb55b66baf04ab0ac69dadaae7c0812.png"
    }, {
        "id": "7",
        "title": "外卖",
        "url": "https://h5.ele.me/msite/",
        "thumb": "http://app.iqilu.com/service/service/images/ed1fcb6d26954cd6a60741853c101100.png"
    }, {
        "id": "8",
        "title": "公交查询",
        "url": "https://map.baidu.com/mobile/webapp/third/transit/",
        "thumb": "http://app.iqilu.com/service/service/images/04f80b4696c34d24ade2b7374b306d87.png"
    }, {
        "id": "9",
        "title": "本地生活",
        "url": "https://i.meituan.com/?utm_campaign=baidu&utm_medium=organic&utm_source=baidu&utm_content=homepage&utm_term=",
        "thumb": "http://app.iqilu.com/service/service/images/f2540e0b11cd4ddb87c9dea13c43d581.png"
    }, {
        "id": "10",
        "title": "滴滴打车",
        "url": "https://common.diditaxi.com.cn/general/webEntry?maptype=wgs&fromlat=39.98096907577634&fromlng=116.30000865410719&channel=xxxx",
        "thumb": "http://app.iqilu.com/service/service/images/52f9b11648824ecabaab73ec246a53ea.png"
    }, {
        "id": "11",
        "title": "百度地图",
        "url": "http://map.baidu.com/mobile/webapp/index/index/foo=bar/vt=map",
        "thumb": "http://app.iqilu.com/service/service/images/1b69eb7739004653b5a1b052be419f94.png"
    }, {
        "id": "12",
        "title": "快递查询",
        "url": "https://m.kuaidi100.com/index_all.html",
        "thumb": "http://app.iqilu.com/service/service/images/e971e8f40407439b9c038f9bec2be9d1.png"
    }, {
        "id": "13",
        "title": "手机归属地",
        "url": "https://m.ip138.com/mobile.html",
        "thumb": "http://app.iqilu.com/service/service/images/126749d725b945b4aece81991bd52076.png"
    }, {
        "id": "14",
        "title": "电信营业厅",
        "url": "https://wapzt.189.cn/",
        "thumb": "http://app.iqilu.com/service/service/images/e66c9aa8e1b444429311e5e5b39f418c.png"
    }, {
        "id": "15",
        "title": "联通营业厅",
        "url": "http://wap.10010.com/",
        "thumb": "http://app.iqilu.com/service/service/images/3144b0974b5f472fb2f10d6a70a87b12.png"
    }, {
        "id": "16",
        "title": "移动营业厅",
        "url": "https://wap.10086.cn/",
        "thumb": "http://app.iqilu.com/service/service/images/67280710e1d746559b851365c062dd41.png"
    }, {
        "id": "17",
        "title": "词典",
        "url": "https://dict.baidu.com",
        "thumb": "http://app.iqilu.com/service/service/images/c1198d6b4e8c41e8b38dfe360bad6368.png"
    }, {
        "id": "18",
        "title": "翻译",
        "url": "http://m.youdao.com",
        "thumb": "http://app.iqilu.com/service/service/images/e30dee1ee71e40e5a8c4c3f69e3e88c2.png"
    }, {
        "id": "19",
        "title": "区号查询",
        "url": "https://m.ip138.com/youbian/",
        "thumb": "http://app.iqilu.com/service/service/images/75b82b4acf1941ee901427994a7d4230.png"
    }, {
        "id": "20",
        "title": "房贷计算器",
        "url": "http://m.dai361.com/",
        "thumb": "http://app.iqilu.com/service/service/images/62e485f820bb4f6da606540c703a72f2.png"
    }, {
        "id": "21",
        "title": "企业招聘",
        "url": "http://m.zhaopin.com/",
        "thumb": "http://app.iqilu.com/service/service/images/b965cf4e29c94daf9d539929eff400eb.png"
    }, {
        "id": "33",
        "title": "重名查询",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/rename/index.htm",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/cmcx.png"
    }, {
        "id": "34",
        "title": "山东人事考试证书邮寄",
        "url": "http://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/sdrskszsyj/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/sdrskszsyj.png"
    }, {
        "id": "35",
        "title": "个人档案状态查询",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/grdaztcxmrhjh/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/grdaztcx.png"
    }, {
        "id": "36",
        "title": "养老机构查询",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/yljgcxfrzyi/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/yljgcx.png"
    }, {
        "id": "37",
        "title": "社区日间照料中心查询",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/sqrjzljgcxmcptb/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/sqrjzlzxcx.png"
    }, {
        "id": "38",
        "title": "山东省地方标准查询",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/sdsdfbzcx/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/sdsdfbzcx.png"
    }, {
        "id": "39",
        "title": "雨水情信息查询",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/sdsysqxxcx/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/ysqxxcx.png"
    }, {
        "id": "40",
        "title": "齐鲁人才政策字典",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/qlrczccd/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/qlrczczd.png"
    }, {
        "id": "41",
        "title": "疫情确诊及密接查询",
        "url": "http://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/blyknjczcx/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/yqqzjmjcx.png"
    }, {
        "id": "42",
        "title": "身份证办理进度查询",
        "url": "http://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/sfzbljdcxprclj/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/sfzbljdcx.png"
    }, {
        "id": "43",
        "title": "疫苗追溯查询",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/ypjdgljyy/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/ymzscx.png"
    }, {
        "id": "44",
        "title": "药品追溯查询",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/sdsypjdglpt/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/ypzscx.png"
    }, {
        "id": "45",
        "title": "重点专科医院",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/zdzk/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/zdzkyy.png"
    }, {
        "id": "46",
        "title": "药品企业查询",
        "url": "http://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/yp/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/ypqycx.png"
    }, {
        "id": "47",
        "title": "外籍人士在鲁工作生活服务指南",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/wjrszlgzshfwzndfszq/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/wjrszlgzshfwzn.png"
    }, {
        "id": "48",
        "title": "法律服务",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/falvfuwu/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/flfw.png"
    }, {
        "id": "49",
        "title": "体育场馆导航",
        "url": "http://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/tycgdh/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/tycgdh.png"
    }, {
        "id": "50",
        "title": "你拍我检",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/npwjkculv/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/npwj.png"
    }, {
        "id": "51",
        "title": "省属企业招聘",
        "url": "http://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/ssqyzp/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/ssqyzp.png"
    }, {
        "id": "52",
        "title": "中小学学籍查询",
        "url": "http://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/zhengwuxjxx/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/zxxxjcx.png"
    }, {
        "id": "53",
        "title": "中国邮政查询",
        "url": "http://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/zgyzkdcx/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/zgyzcx.png"
    }, {
        "id": "54",
        "title": "政府采购信息查询",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/zzcgxxcx/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/zfcgxxcx.png"
    }, {
        "id": "55",
        "title": "山东省职业技能证书查询",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/sdszyjnzscx/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/sdszyjnzscx.png"
    }, {
        "id": "56",
        "title": "高速路况查询",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/gslkcx/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/gslkcx.png"
    }, {
        "id": "57",
        "title": "统一社会信用代码查询",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/fgwtyshxydmcx/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/tyshxydmcx.png"
    }, {
        "id": "58",
        "title": "法人及其他组织信用查询",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/fgwfrjqtzzcx/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/frjqtzzxycx.png"
    }, {
        "id": "59",
        "title": "守信红名单",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/fgwsxredmd/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/sxhmd.png"
    }, {
        "id": "60",
        "title": "失信黑名单",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/fgwsxblackmd/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/shixin.png"
    }, {
        "id": "61",
        "title": "行政许可公示",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/fgwxzxkgs/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/xzxkgs.png"
    }, {
        "id": "62",
        "title": "行政处罚公示",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/fgwxzcfgs/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/xzcfgs.png"
    }, {
        "id": "63",
        "title": "全省社保通查",
        "url": "https://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/sdsrst/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/xzxkgs.png"
    }, {
        "id": "64",
        "title": "住房公积金服务大厅",
        "url": "http://isdapp.shandong.gov.cn/jmopenpub/jmopen_files/webapp/html5/zfgjjfwdt/index.html",
        "thumb": "https://img11.iqilu.com/0/publicfuwuicon/xzxkgs.png"
    }],
    "errmsg": "",
    "t": 8.390869140625
};
let str = "本地生活, 百度地图, 百度出行, 手机归属地, 外卖, 翻译, 词典, 家政, 重名查询, 企业招聘, 区号查询, 个人档案状态查询, 养老机构查询, 山东人事考试证书邮寄, 山东省地方标准查询, 天气预报, 身份证办理进度查询, 社区日间照料中心查询, 失信黑名单, 疫情确诊及密接查询, 齐鲁人才政策字典, 重点专科医院, 药品追溯查询, 政府采购信息查询, 疫苗追溯查询, 省属企业招聘, 法律服务, 守信红名单, 外籍人士在鲁工作生活服务指南, 你拍我检, 统一社会信用代码查询, 体育场馆导航, 中国邮政查询, 中小学学籍查询, 山东省职业技能证书查询, 法人及其他组织信用查询, 房贷计算器, 住房公积金服务大厅, PM2 .5 查询, 行政许可公示, 行政处罚公示, 药品企业查询, 全省社保通查";
let arr = str.replace(/\s/g, '').split(',');
let arr2 = []
obj.data.filter(function(item) {
    if (arr.includes(item.title)) {
        arr2.push(item)
    }
})
console.log(arr2);